version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  post_build:
    commands:
      - npm run build
      - npx prisma generate
      - echo "Starting database migration..."
      - npx prisma migrate deploy
      - echo "Database migration completed."
